"""Generate small language bindings from the canonical housing JSON Schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "contracts" / "housing.schema.json"
PYTHON_PATH = (
    ROOT / "contracts" / "generated" / "python" / "property_playground_contracts" / "models.py"
)
TYPESCRIPT_PATH = ROOT / "portal" / "lib" / "generated" / "contracts.ts"
JAVA_DIRECTORY = (
    ROOT
    / "services"
    / "market-api"
    / "src"
    / "main"
    / "java"
    / "com"
    / "propertyplayground"
    / "contracts"
)

HEADER = "Generated from contracts/housing.schema.json by scripts/generate_contracts.py."


def python_type(specification: dict[str, Any]) -> str:
    if "const" in specification:
        return f"Literal[{json.dumps(specification['const'])}]"
    return {"number": "float", "integer": "int", "string": "str"}[specification["type"]]


def python_field(specification: dict[str, Any], required: bool) -> str:
    arguments = []
    constraint_names = {
        "exclusiveMinimum": "gt",
        "minimum": "ge",
        "maximum": "le",
    }
    for schema_name, field_name in constraint_names.items():
        if schema_name in specification:
            arguments.append(f"{field_name}={specification[schema_name]!r}")
    if "examples" in specification:
        arguments.append(f"examples={specification['examples']!r}")

    if "default" in specification:
        default = json.dumps(specification["default"])
        if arguments:
            return f"Field(default={default}, {', '.join(arguments)})"
        return default
    if arguments:
        return f"Field({', '.join(arguments)})"
    return "..." if required else "None"


def render_python(definitions: dict[str, Any]) -> str:
    lines = [
        f'"""{HEADER}\n\nDo not edit this file directly.\n"""',
        "",
        "from typing import Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "",
    ]
    for name, definition in definitions.items():
        lines.extend([f"class {name}(BaseModel):", '    """Shared API contract."""'])
        if definition.get("additionalProperties") is False:
            lines.extend(["", '    model_config = ConfigDict(extra="forbid")'])
        required = set(definition.get("required", []))
        for property_name, specification in definition["properties"].items():
            annotation = python_type(specification)
            default = python_field(specification, property_name in required)
            lines.append(f"    {property_name}: {annotation} = {default}")
        lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def typescript_type(specification: dict[str, Any]) -> str:
    if "const" in specification:
        return json.dumps(specification["const"])
    return {"number": "number", "integer": "number", "string": "string"}[specification["type"]]


def render_typescript(definitions: dict[str, Any]) -> str:
    lines = [f"// {HEADER}", "// Do not edit this file directly.", ""]
    for name, definition in definitions.items():
        required = set(definition.get("required", []))
        lines.append(f"export type {name} = {{")
        for property_name, specification in definition["properties"].items():
            optional = "" if property_name in required else "?"
            lines.append(f"  {property_name}{optional}: {typescript_type(specification)};")
        lines.extend(["};", ""])
    return "\n".join(lines)


def java_annotation(specification: dict[str, Any]) -> list[str]:
    annotations: list[str] = []
    value_type = specification["type"]
    if specification.get("exclusiveMinimum") == 0:
        annotations.append("@Positive")
    if "minimum" in specification:
        annotation = "Min" if value_type == "integer" else "DecimalMin"
        value = specification["minimum"]
        rendered = str(value) if value_type == "integer" else f'"{value}"'
        annotations.append(f"@{annotation}({rendered})")
    if "maximum" in specification:
        annotation = "Max" if value_type == "integer" else "DecimalMax"
        value = specification["maximum"]
        rendered = str(value) if value_type == "integer" else f'"{value}"'
        annotations.append(f"@{annotation}({rendered})")
    return annotations


def java_type(specification: dict[str, Any]) -> str:
    return {"number": "double", "integer": "int", "string": "String"}[specification["type"]]


def camel_case(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(part.capitalize() for part in tail)


def render_java(name: str, definition: dict[str, Any]) -> str:
    properties = list(definition["properties"].items())
    annotation_names = {
        item[1:].split("(", maxsplit=1)[0]
        for _, specification in properties
        for item in java_annotation(specification)
    }
    imports = []
    if any("_" in property_name for property_name, _ in properties):
        imports.append("import com.fasterxml.jackson.annotation.JsonProperty;")
    imports.extend(
        f"import jakarta.validation.constraints.{item};" for item in sorted(annotation_names)
    )
    lines = [
        "package com.propertyplayground.contracts;",
        "",
        *imports,
        "",
        f"// {HEADER}",
        f"public record {name}(",
    ]
    fields = []
    for property_name, specification in properties:
        annotations = java_annotation(specification)
        if "_" in property_name:
            annotations.append(f'@JsonProperty("{property_name}")')
        prefix = " ".join(annotations)
        if prefix:
            prefix += " "
        fields.append(f"        {prefix}{java_type(specification)} {camel_case(property_name)}")
    lines.append(",\n".join(fields) + ") {")
    lines.append("}")
    return "\n".join(lines) + "\n"


def generated_files() -> dict[Path, str]:
    definitions = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))["$defs"]
    outputs = {
        PYTHON_PATH: render_python(definitions),
        TYPESCRIPT_PATH: render_typescript(definitions),
    }
    for name in ("HousingFeatures", "PredictionResponse"):
        outputs[JAVA_DIRECTORY / f"{name}.java"] = render_java(name, definitions[name])
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated bindings are stale")
    options = parser.parse_args()
    stale: list[Path] = []
    for path, content in generated_files().items():
        if options.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        paths = ", ".join(map(str, stale))
        raise SystemExit(f"Generated contracts are stale: {paths}. Run `make contracts`.")


if __name__ == "__main__":
    main()
